version: '3.8'
services:

  postgres:
    image: postgres:latest
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devops
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data



  devopsapp:
    image: devopsapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/devops
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mynetwork



networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
